// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddTask(arg1:string):Promise<backend.Task>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetTasks():Promise<Array<backend.Task>>;

export function ToggleDone(arg1:string):Promise<backend.Task>;

export function UpdateTask(arg1:string,arg2:string):Promise<backend.Task>;
