// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['backend']['TodoService']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['TodoService']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['backend']['TodoService']['GetTasks']();
}

export function ToggleDone(arg1) {
  return window['go']['backend']['TodoService']['ToggleDone'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['backend']['TodoService']['UpdateTask'](arg1, arg2);
}
